-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 17:12:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u-know
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u-know
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u-know` DEFAULT CHARACTER SET utf8mb3 ;
USE `u-know` ;

-- -----------------------------------------------------
-- Table `u-know`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u-know`.`user` ;

CREATE TABLE IF NOT EXISTS `u-know`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `credit_balance` INT NULL DEFAULT 1000,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u-know`.`content` ;

CREATE TABLE IF NOT EXISTS `u-know`.`content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `price` INT NULL DEFAULT 200,
  `author_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `categorie` VARCHAR(405) NOT NULL,
  `dificulty` VARCHAR(405) NOT NULL,
  `sales` INT NULL,
  `aproved` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `author_id_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `content_author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u-know`.`comments` ;

CREATE TABLE IF NOT EXISTS `u-know`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_id` INT NOT NULL,
  `text` VARCHAR(200) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `content_id_idx` (`content_id` ASC) VISIBLE,
  CONSTRAINT `content_id`
    FOREIGN KEY (`content_id`)
    REFERENCES `u-know`.`content` (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u-know`.`purchase` ;

CREATE TABLE IF NOT EXISTS `u-know`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `purchasecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `purchase_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u-know`.`rating` ;

CREATE TABLE IF NOT EXISTS `u-know`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `value` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `content_id_idx` (`content_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `rating_content_id`
    FOREIGN KEY (`content_id`)
    REFERENCES `u-know`.`content` (`id`),
  CONSTRAINT `rating_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`purchase_has_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u-know`.`purchase_has_content` ;

CREATE TABLE IF NOT EXISTS `u-know`.`purchase_has_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_id` INT NOT NULL,
  `content_id` INT NOT NULL,
  INDEX `fk_purchase_has_content_content1_idx` (`content_id` ASC) VISIBLE,
  INDEX `fk_purchase_has_content_purchase1_idx` (`purchase_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_has_content_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `u-know`.`purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_has_content_content1`
    FOREIGN KEY (`content_id`)
    REFERENCES `u-know`.`content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
