-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 20:47:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u-know
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u-know
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u-know` DEFAULT CHARACTER SET utf8mb3 ;
USE `u-know` ;

-- -----------------------------------------------------
-- Table `u-know`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categorie_id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `credit_balance` INT NOT NULL DEFAULT '1000',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`dificulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`dificulty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dificulty_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `price` INT NOT NULL DEFAULT '200',
  `updated_at` TIMESTAMP NOT NULL,
  `categorie_id` INT NOT NULL,
  `dificulty_id` INT NOT NULL,
  `sales` INT NOT NULL DEFAULT '0',
  `aproved` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `content_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `author_id_idx` (`author_id` ASC) VISIBLE,
  INDEX `content_categorie_id_idx` (`categorie_id` ASC) VISIBLE,
  INDEX `content_dificulty_id_idx` (`dificulty_id` ASC) VISIBLE,
  CONSTRAINT `content_author_id_fk`
    FOREIGN KEY (`author_id`)
    REFERENCES `u-know`.`user` (`id`),
  CONSTRAINT `content_categorie_id_fk`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `u-know`.`categorie` (`id`),
  CONSTRAINT `content_dificulty_id_fk`
    FOREIGN KEY (`dificulty_id`)
    REFERENCES `u-know`.`dificulty` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_comments_id` INT NOT NULL,
  `text` VARCHAR(200) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `content_id_idx` (`content_comments_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `comment_content_id_fk`
    FOREIGN KEY (`content_comments_id`)
    REFERENCES `u-know`.`content` (`id`),
  CONSTRAINT `comment_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `sender_id_idx` (`sender_id` ASC) VISIBLE,
  INDEX `receiver_id_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `receiver_id_fk`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `u-know`.`user` (`id`),
  CONSTRAINT `sender_id_fk`
    FOREIGN KEY (`sender_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `purchaseDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `purchase_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `purchase_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`purchase_has_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`purchase_has_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_id` INT NOT NULL,
  `content_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `purchase_has_content_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `purchase_has_content_content_id_idx` (`content_id` ASC) VISIBLE,
  INDEX `purchase_has_content_purchase_id_idx` (`purchase_id` ASC) VISIBLE,
  CONSTRAINT `purchase_has_content_content_id_fk`
    FOREIGN KEY (`content_id`)
    REFERENCES `u-know`.`content` (`id`),
  CONSTRAINT `purchase_has_content_purchase_id_fk`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `u-know`.`purchase` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `u-know`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u-know`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_rating_id` INT NOT NULL,
  `user_rating_id` INT NOT NULL,
  `value` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rating_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `content_id_idx` (`content_rating_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_rating_id` ASC) VISIBLE,
  CONSTRAINT `rating_content_id_fk`
    FOREIGN KEY (`content_rating_id`)
    REFERENCES `u-know`.`content` (`id`),
  CONSTRAINT `rating_user_id_fk`
    FOREIGN KEY (`user_rating_id`)
    REFERENCES `u-know`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
